var words = {};

words["a"]       = { family: "A"        , short: "lex 1" };
words["ba"]      = { family: "BA"       , short: "predication" };
words["ban"]     = { family: "R"        , short: "language"              , long: "x1 is a language/dialect used by x2 to express x3 (predicate)", lojban: "bangu" }
words["be"]      = { family: "BA"       , short: "relation" };
words["bi"]      = { family: "BA"       , short: "event" };
words["bla"]     = { family: "R"        , short: "future"                , long: "x1 (abstraction) is in the future/after x2", lojban: "balvi" }
words["bria"]    = { family: "R"        , short: "arm"                   , long: "x1 (abstraction) is a/the arm of x2", lojban: "cabna" }
words["ca"]      = { family: "CA"       , short: "or" };
words["ce"]      = { family: "CA"       , short: "and" };
words["ci"]      = { family: "CA"       , short: "connective ?" };
words["cna"]     = { family: "R"        , short: "present"               , long: "x1 is in the present of/simultaneous with x2", lojban: "birka" }
words["co"]      = { family: "CA"       , short: "iif" };
words["cti'a"]   = { family: "R"        , short: "eat"                   , long: "x1 eats x2", lojban: "citka" }
words["cu"]      = { family: "CA"       , short: "whether-or-not" };
words["dju"]     = { family: "R"        , short: "know"                  , long: "x1 knows fact(s) x2 (abstraction) about subject x3 by epistemology x4", lojban: "djuno" }
words["du"]      = { family: "DU"       , short: "modal" };
words["e'o"]     = { family: "XA"       , short: "request" };
words["e"]       = { family: "E"        , short: "lex 2" };
words["fa"]      = { family: "FA"       , short: "x1" };
words["fe"]      = { family: "FA"       , short: "x2" };
words["fi"]      = { family: "FA"       , short: "x3" };
words["fo"]      = { family: "FA"       , short: "x4" };
words["fu"]      = { family: "FA"       , short: "x5" };
words["i"]       = { family: "I"        , short: "lex 3" };
words["ja"]      = { family: "JA"       , short: "or" };
words["je"]      = { family: "JA"       , short: "connective ?" };
words["ji"]      = { family: "JA"       , short: "and" };
words["jo"]      = { family: "JA"       , short: "iif" };
words["ju"]      = { family: "JA"       , short: "whether-or-not" };
words["ka"]      = { family: "KA"       , short: "negation" };
words["kai"]     = { family: "KAI"      , short: "negation" };
words["ma'i"]    = { family: "MA"       , short: "this" };
words["ma'o"]    = { family: "MA"       , short: "that" };
words["ma'u"]    = { family: "MA"       , short: "that younder" };
words["ma"]      = { family: "MA"       , short: "?" };
words["mai"]     = { family: "MA"       , short: "something #1" };
words["mei"]     = { family: "MA"       , short: "something #2" };
words["mi"]      = { family: "MA"       , short: "me" };
words["mia"]     = { family: "MA"       , short: "they #1" };
words["mie"]     = { family: "MA"       , short: "they #2" };
words["mii"]     = { family: "MA"       , short: "they #3" };
words["mio"]     = { family: "MA"       , short: "they #4" };
words["miu"]     = { family: "MA"       , short: "they #5" };
words["mo'a"]    = { family: "MA"       , short: "you (imperative)" };
words["mo"]      = { family: "MA"       , short: "you" };
words["moi"]     = { family: "MA"       , short: "something #3" };
words["mua"]     = { family: "MA"       , short: "they #6" };
words["mue"]     = { family: "MA"       , short: "they #7" };
words["mui"]     = { family: "MA"       , short: "they #8" };
words["muo"]     = { family: "MA"       , short: "they #9" };
words["muu"]     = { family: "MA"       , short: "they #10" };
words["o"]       = { family: "O"        , short: "lex 4" };
words["pa'a"]    = { family: "PA"       , short: "open free scope" };
words["pa'e"]    = { family: "PA"       , short: "non-standard" };
words["pa"]      = { family: "PA"       , short: "{" };
words["pai"]     = { family: "PAI"      , short: "}" };
words["pe'a"]    = { family: "PE"       , short: "parenthetical" };
words["pe"]      = { family: "PE"       , short: "discursive" };
words["pi'a"]    = { family: "PE"       , short: "associated with" };
words["pi"]      = { family: "PE"       , short: "free restrictive adverbial" };
words["po"]      = { family: "PE"       , short: "free non-restrictive adverbial" };
words["poi"]     = { family: "PE"       , short: "=" };
words["pu"]      = { family: "PE"       , short: "subscript" };
words["sa'a"]    = { family: "SA"       , short: "other than" };
words["sa'e"]    = { family: "SA"       , short: "not" };
words["sa'i"]    = { family: "SA"       , short: "not really" };
words["sa"]      = { family: "SA"       , short: "name" };
words["se"]      = { family: "SA"       , short: "x1 &#8652; x2" };
words["sei"]     = { family: "SA"       , short: "x1 &#8652; x?" };
words["si"]      = { family: "SA"       , short: "x1 &#8652; x3" };
words["so"]      = { family: "SA"       , short: "x1 &#8652; x4" };
words["soi"]     = { family: "SA"       , short: "referent of" };
words["su"]      = { family: "SA"       , short: "x1 &#8652; x5" };
words["ta"]      = { family: "TA"       , short: "0" };
words["tia"]     = { family: "TA"       , short: "1" };
words["tie"]     = { family: "TA"       , short: "2" };
words["tii"]     = { family: "TA"       , short: "3" };
words["tio"]     = { family: "TA"       , short: "4" };
words["tiu"]     = { family: "TA"       , short: "5" };
words["tu'a"]    = { family: "TA"       , short: "B (11)" };
words["tu'e"]    = { family: "TA"       , short: "C (12)" };
words["tu'i"]    = { family: "TA"       , short: "D (13)" };
words["tu'o"]    = { family: "TA"       , short: "E (14)" };
words["tu'u"]    = { family: "TA"       , short: "F (15)" };
words["tua"]     = { family: "TA"       , short: "6" };
words["tue"]     = { family: "TA"       , short: "7" };
words["tui"]     = { family: "TA"       , short: "8" };
words["tuo"]     = { family: "TA"       , short: "9" };
words["tuu"]     = { family: "TA"       , short: "A (10)" };
words["u"]       = { family: "U"        , short: "lex +" };
words["ui"]      = { family: "XA"       , short: "happy" };
words["va"]      = { family: "FA"       , short: "x+" };
words["ve"]      = { family: "FA"       , short: "x?" };
words["vi"]      = { family: "FA"       , short: "restrictive adverbial" };
words["vo"]      = { family: "FA"       , short: "non-restrictive adverbial" };
words["vu"]      = { family: "FA"       , short: "subordinating adverbial" };
words["xu'u"]    = { family: "XA"       , short: "(indirect ?)" };
words["xu"]      = { family: "XA"       , short: "true ?" };
words["xu"]      = { family: "XA"       , short: "true ?"                , long: "true/false question marker", lojban: "xu" }
words["xua"]     = { family: "XA"       , short: "strong" };
words["xue"]     = { family: "XA"       , short: "moderate" };
words["xui"]     = { family: "XA"       , short: "neutral" };
words["xuo"]     = { family: "XA"       , short: "weak" };
words["xuu"]     = { family: "XA"       , short: "intensity ?" };

// Roots   
shortDescriptions["cki'a"] = "write";
shortDescriptions["cku'a"] = "book";
shortDescriptions["cti'a"] = "eat";
shortDescriptions["du'an"] = "give";
shortDescriptions["dzu"] = "walk";
shortDescriptions["ma'un"] = "male";
shortDescriptions["mi'un"] = "female";
shortDescriptions["mla'u"] = "cat";
shortDescriptions["pin"] = "drink";
shortDescriptions["plie"] = "apple";
shortDescriptions["pre'i"] = "parent";
shortDescriptions["pre"] = "person";
shortDescriptions["pru"] = "past";
shortDescriptions["zda'i"] = "home";
shortDescriptions["zva"] = "present at";
shortDescriptions["vla"] = "talk";
shortDescriptions["zdu"] = "do";
shortDescriptions["dju"] = "know";


module.exports.shortDescriptions = shortDescriptions;
